"""add senha_temporaria fields

Revision ID: 6ea72fd2c856
Revises: 9580fce70f16
Create Date: 2025-05-20 07:05:38.231371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea72fd2c856'
down_revision: Union[str, None] = '9580fce70f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('senha_temporaria', sa.String(length=100), nullable=True))
    op.add_column('usuario', sa.Column('data_senha_temporaria', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'data_senha_temporaria')
    op.drop_column('usuario', 'senha_temporaria')
    # ### end Alembic commands ###
