"""criação inicial

Revision ID: 9580fce70f16
Revises: 
Create Date: 2025-05-19 12:43:24.755891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9580fce70f16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('endereco', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('conta_bloqueada', sa.Boolean(), nullable=True),
    sa.Column('tentativas_login', sa.Integer(), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('autenticacao_dois_fatores', sa.Boolean(), nullable=True),
    sa.Column('chave_secreta_2fa', sa.String(length=32), nullable=True),
    sa.Column('data_bloqueio', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('meio_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_registro', sa.String(length=50), nullable=False),
    sa.Column('placa_veiculo', sa.String(length=50), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('hora', sa.String(length=5), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passagem')
    op.drop_table('meio_pagamento')
    op.drop_table('usuario')
    # ### end Alembic commands ###
